<?php
date_default_timezone_set("Asia/Calcutta");
//ENTER THE NAME OF THE DATABASE SERVER YOU ARE CONNECTING TO. NORMALLY SET TO "localhost"


define("DATABASE_SERVER", "localhost");

define("DATABASE_NAME", "tanzania");

//ENTER THE USERNAME THAT CONNECTS TO YOUR DATABASE
define("DATABASE_USERNAME", "root");

//ENTER THE PASSWORD FOR YOUR DATABASE USER
define("DATABASE_PASSWORD", "");
//ENTER THE DOMAIN NAME FOR YOUR APPLICATION

//DEFINE PAGINATION LIMIT OF LISTING PAGE


?>